### ISSUE TITLE
Concrete working example

### ISSUE THREAD

**Issue by benjaminkovacevic** [vankasteelj/torrent-tracker-health#4]
Please provide a concrete working example.. I got error 

Error: Cannot find module 'URIjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/html/torrent-tracker-health/node_modules/torrent-tracker/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by vankasteelj** [comment]
Here's a concrete example from the readme:

In cli: 
```
npm install torrent-tracker-health
```

Then in node:
```js
var torrentHealth = require('torrent-tracker-health');
var magnet = 'magnet:?xt=urn:btih:9A7290F4021048D2C176A84828E441FCB5400FB1&dn=charlie+chaplin+15+short+films+1914+1917+dvdrip&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://glotorrents.pw:6969/announce&tr=udp://tracker.openbittorrent.com:80/announce';

torrentHealth(magnet).then(console.log).catch(console.error)
```

Output is, as of may 2022, is: 

```js
 {
  seeds: 4,
  peers: 1,
  results: [
    {
      tracker: 'udp://tracker.coppersurfer.tk:6969/announce',
      error: 'timed out'
    },
    {
      tracker: 'udp://glotorrents.pw:6969/announce',
      error: 'timed out'
    },
    {
      tracker: 'udp://tracker.openbittorrent.com:80/announce',
      response_time: 119,
      seeds: 4,
      peers: 1
    }
  ]
}
```
